version: '3.4'

volumes:
    db_volume:

services:
    db:
        image: postgres:latest
        container_name: postgres-db
        ports:
            - "5432"
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - db_volume:/var/lib/postgresql/data
    api:
        build: ./SquaresAPI
        container_name: squares-api
        restart: always
        ports:
            - "8085:80"
        depends_on:
            - db
        environment:
            ConnectionStrings__SquaresDatabase: ${CONNECTION_STRING}
    web:
        image: dpage/pgadmin4:latest
        container_name: pg-admin
        restart: always
        ports:
            - "8080:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}